<?php
/** Request Monitor MU runtime helpers. Version: 0.6.0 */
if (!defined('ABSPATH') || defined('RRT_RUNTIME_LOADED')) return;
define('RRT_RUNTIME_LOADED', true);

function rrt_mu_server($key,$limit=1000){if(!isset($_SERVER[$key])||!is_scalar($_SERVER[$key]))return null;$v=(string)$_SERVER[$key];return $v===''?null:substr($v,0,$limit);}
function rrt_mu_timestamp($time){$ms=(int)(($time-floor($time))*1000);return gmdate('Y-m-d\TH:i:s',(int)$time).'.'.sprintf('%03d',$ms).'Z';}
function rrt_mu_snapshot(){$out=array('cpu_user_ms'=>null,'cpu_sys_ms'=>null,'cpu_total_ms'=>null,'minor_faults'=>null,'major_faults'=>null,'voluntary_ctx'=>null,'involuntary_ctx'=>null,'block_in'=>null,'block_out'=>null,'rchar'=>null,'wchar'=>null,'read_bytes'=>null,'write_bytes'=>null,'syscr'=>null,'syscw'=>null);if(function_exists('getrusage')){$r=getrusage();$u=(($r['ru_utime.tv_sec']??0)*1000)+(($r['ru_utime.tv_usec']??0)/1000);$s=(($r['ru_stime.tv_sec']??0)*1000)+(($r['ru_stime.tv_usec']??0)/1000);$out['cpu_user_ms']=$u;$out['cpu_sys_ms']=$s;$out['cpu_total_ms']=$u+$s;foreach(array('ru_minflt'=>'minor_faults','ru_majflt'=>'major_faults','ru_nvcsw'=>'voluntary_ctx','ru_nivcsw'=>'involuntary_ctx','ru_inblock'=>'block_in','ru_oublock'=>'block_out') as $rk=>$ok)$out[$ok]=isset($r[$rk])?(int)$r[$rk]:null;}if(is_readable('/proc/self/io')){$lines=@file('/proc/self/io',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);if(is_array($lines))foreach($lines as $line){if(strpos($line,':')===false)continue;list($k,$v)=array_map('trim',explode(':',$line,2));if(array_key_exists($k,$out)&&is_numeric($v))$out[$k]=(int)$v;}}return $out;}
function rrt_mu_delta($start,$end){$out=array();foreach($end as $k=>$v){$b=array_key_exists($k,$start)?$start[$k]:null;if($v===null||$b===null){$out[$k]=null;continue;}$d=$v-$b;$out[$k]=strpos($k,'_ms')!==false?round($d,3):$d;}return $out;}
function rrt_mu_log_file(){$dir=WP_CONTENT_DIR.'/rocket-request-tracer';if(!is_dir($dir))@wp_mkdir_p($dir);if(!file_exists($dir.'/index.php'))@file_put_contents($dir.'/index.php',"<?php\nexit;\n");if(!file_exists($dir.'/.htaccess'))@file_put_contents($dir.'/.htaccess',"Require all denied\nDeny from all\n");$seed=defined('AUTH_SALT')?AUTH_SALT:ABSPATH;$file=$dir.'/trace-'.substr(hash('sha256',$seed),0,16).'.php';if(!file_exists($file))@file_put_contents($file,"<?php exit; __halt_compiler(); ?>\n",LOCK_EX);return $file;}
function rrt_mu_rotate($file){$max=max(1,(int)get_option('rrt_max_log_mb',25));if(!is_file($file)||@filesize($file)<=($max*1048576))return;$rot=preg_replace('/\.php$/','-'.gmdate('Ymd-His').'.php',$file);if(@rename($file,$rot))@file_put_contents($file,"<?php exit; __halt_compiler(); ?>\n",LOCK_EX);$files=glob(dirname($file).'/trace-*.php');if(is_array($files)&&count($files)>4){usort($files,function($a,$b){return @filemtime($a)<=>@filemtime($b);});while(count($files)>4){$old=array_shift($files);if($old!==$file)@unlink($old);}}}
function rrt_mu_write($event){$file=rrt_mu_log_file();rrt_mu_rotate($file);$json=function_exists('wp_json_encode')?wp_json_encode($event,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):json_encode($event,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if($json!==false)@file_put_contents($file,$json."\n",FILE_APPEND|LOCK_EX);}
function rrt_mu_safe_query(){$out=array();foreach($_GET as $key=>$value){$key=(string)$key;$allowed=strpos($key,'filter_')===0||strpos($key,'query_type_')===0||in_array($key,array('orderby','paged','page','product_cat','product_tag','min_price','max_price','s','rest_route'),true);if(!$allowed)continue;if(is_scalar($value))$out[$key]=substr((string)$value,0,500);elseif(is_array($value)){$vals=array();foreach(array_slice($value,0,20) as $v)$vals[]=is_scalar($v)?substr((string)$v,0,500):'[complex]';$out[$key]=$vals;}}ksort($out);return $out;}
function rrt_mu_normalize_path($path,$template=false){$path=rawurldecode((string)$path);$path=preg_replace('#/+#','/',$path);if($path==='')$path='/';if($path!=='/')$path=rtrim($path,'/');if(!$template)return $path;$segments=explode('/',$path);foreach($segments as &$segment){if($segment==='')continue;if(preg_match('/^[0-9]+$/',$segment))$segment='{n}';elseif(preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',$segment))$segment='{uuid}';elseif(preg_match('/^[0-9a-f]{24,}$/i',$segment))$segment='{hex}';}unset($segment);$p=implode('/',$segments);return $p===''?'/':$p;}
function rrt_mu_value_hash($value){if(is_array($value)){$n=array();foreach($value as $k=>$v)$n[(string)$k]=rrt_mu_value_hash($v);ksort($n);return substr(hash('sha256',json_encode($n)),0,16);}if(is_scalar($value)||$value===null)return substr(hash('sha256',(string)$value),0,16);return 'complex';}
function rrt_mu_query_fingerprints(){$keys=array_map('strval',array_keys($_GET));sort($keys,SORT_STRING);$keys=array_slice($keys,0,100);$hashes=array();foreach($keys as $key)if(array_key_exists($key,$_GET))$hashes[$key]=rrt_mu_value_hash($_GET[$key]);return array('query_keys'=>$keys,'query_shape_fingerprint'=>substr(hash('sha256',implode('|',$keys)),0,16),'query_fingerprint'=>substr(hash('sha256',json_encode($hashes,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)),0,16));}
function rrt_mu_request_action(){if(isset($_REQUEST['action'])&&is_scalar($_REQUEST['action']))return substr((string)$_REQUEST['action'],0,200);if(isset($_GET['wc-ajax'])&&is_scalar($_GET['wc-ajax']))return 'wc-ajax:'.substr((string)$_GET['wc-ajax'],0,200);return '';}
function rrt_mu_request_type($path){if((defined('WP_CLI')&&WP_CLI)||PHP_SAPI==='cli')return 'cli';if(defined('DOING_CRON')&&DOING_CRON)return 'cron';if((defined('DOING_AJAX')&&DOING_AJAX)||substr($path,-15)==='/admin-ajax.php')return 'ajax';if(isset($_GET['rest_route'])||strpos($path,'/wp-json/')===0||$path==='/wp-json')return 'rest';if(strpos($path,'/wp-admin/')===0||$path==='/wp-admin')return 'admin';return 'front';}
function rrt_mu_default_scope(){return array('types'=>array('front','admin','ajax','rest','cron'),'methods'=>array(),'include_paths'=>array(),'exclude_paths'=>array(),'include_actions'=>array(),'exclude_actions'=>array());}
function rrt_mu_scope(){$s=get_option('rrt_trace_scope',array());if(!is_array($s))$s=array();$s=array_merge(rrt_mu_default_scope(),$s);foreach($s as $k=>$v)$s[$k]=is_array($v)?array_values(array_filter(array_map('strval',$v),function($x){return $x!=='';})):array();return $s;}
function rrt_mu_glob_match($value,$patterns){foreach((array)$patterns as $pattern){if($pattern==='')continue;if(function_exists('fnmatch')&&fnmatch($pattern,$value,FNM_CASEFOLD))return true;$q=preg_quote($pattern,'#');if(preg_match('#^'.str_replace(array('\\*','\\?'),array('.*','.'),$q).'$#i',$value))return true;}return false;}
function rrt_mu_scope_match($d,$s){if(!empty($s['types'])&&!in_array($d['type'],$s['types'],true))return false;if(!empty($s['methods'])&&!in_array(strtoupper($d['method']),array_map('strtoupper',$s['methods']),true))return false;if(!empty($s['include_paths'])&&!rrt_mu_glob_match($d['path'],$s['include_paths']))return false;if(!empty($s['exclude_paths'])&&rrt_mu_glob_match($d['path'],$s['exclude_paths']))return false;if(!empty($s['include_actions'])&&!rrt_mu_glob_match($d['action'],$s['include_actions']))return false;if(!empty($s['exclude_actions'])&&rrt_mu_glob_match($d['action'],$s['exclude_actions']))return false;return true;}
function rrt_mu_is_own_cli(){if(!((defined('WP_CLI')&&WP_CLI)||PHP_SAPI==='cli'))return false;$argv=isset($_SERVER['argv'])&&is_array($_SERVER['argv'])?implode(' ',$_SERVER['argv']):'';return stripos($argv,'request-monitor')!==false;}
function rrt_mu_should_trace($descriptor){if(rrt_mu_is_own_cli())return false;if(isset($_REQUEST['page'])&&$_REQUEST['page']==='rocket-request-tracer')return false;if(isset($_REQUEST['action'])&&in_array($_REQUEST['action'],array('rrt_settings','rrt_capture','rrt_stop','rrt_clear','rrt_download','rrt_repair_mu'),true))return false;return rrt_mu_scope_match($descriptor,rrt_mu_scope());}
function rrt_mu_classify($wall,$ratio){if($wall<750)return 'FAST';if($ratio===null)return 'UNKNOWN';if($ratio>=0.70)return 'CPU_BOUND';if($ratio<=0.25)return 'WAIT_BOUND';return 'MIXED';}
function rrt_mu_phase_durations($phases,$end){$out=array();$prev_name='mu_loaded';$prev=$phases['mu_loaded']??null;foreach($phases as $name=>$time){if($name==='mu_loaded'||$prev===null)continue;$out[$prev_name.'_to_'.$name.'_ms']=round(($time-$prev)*1000,3);$prev_name=$name;$prev=$time;}if($prev!==null)$out[$prev_name.'_to_shutdown_ms']=round(($end-$prev)*1000,3);return $out;}
