<?php
if (!defined('ABSPATH')) exit;

final class Request_Monitor_Admin {
    const NONCE='rrt_admin_action';
    private static $instance=null;
    public static function instance(){if(self::$instance===null)self::$instance=new self();return self::$instance;}
    private function __construct(){add_action('admin_init',array($this,'ensure_mu'));add_action('admin_menu',array($this,'menu'));add_action('admin_post_rrt_settings',array($this,'settings'));add_action('admin_post_rrt_capture',array($this,'capture'));add_action('admin_post_rrt_stop',array($this,'stop'));add_action('admin_post_rrt_clear',array($this,'clear'));add_action('admin_post_rrt_download',array($this,'download'));add_action('admin_post_rrt_repair_mu',array($this,'repair'));}
    public function ensure_mu(){if(current_user_can('manage_options')&&!Request_Monitor_Core::mu_healthy())Request_Monitor_Core::install_mu();}
    public function menu(){add_management_page('Request Monitor','Request Monitor','manage_options','rocket-request-tracer',array($this,'render'));}
    private function auth(){if(!current_user_can('manage_options'))wp_die('Insufficient permissions.');check_admin_referer(self::NONCE);}
    private function redirect(){wp_safe_redirect(admin_url('tools.php?page=rocket-request-tracer'));exit;}

    public function settings(){$this->auth();update_option(Request_Monitor_Core::OPT_MAX_MB,max(1,min(250,(int)($_POST['max_mb']??25))),false);update_option(Request_Monitor_Core::OPT_SLOW_MS,max(250,min(60000,(int)($_POST['slow_ms']??1500))),false);update_option(Request_Monitor_Core::OPT_CALLBACK_FLOOR,max(0.1,min(1000,(float)($_POST['callback_floor']??5))),false);Request_Monitor_Core::save_scope(array('types'=>$_POST['scope_types']??array(),'methods'=>$_POST['scope_methods']??'','include_paths'=>$_POST['include_paths']??'','exclude_paths'=>$_POST['exclude_paths']??'','include_actions'=>$_POST['include_actions']??'','exclude_actions'=>$_POST['exclude_actions']??''));$this->redirect();}
    public function capture(){$this->auth();$seconds=max(Request_Monitor_Core::MIN_CAPTURE_SECONDS,min(Request_Monitor_Core::MAX_CAPTURE_SECONDS,(int)($_POST['duration']??30)));$profile=$_POST['profile']??'light';if(empty($_POST['keep_log']))Request_Monitor_Store::clear_logs();Request_Monitor_Core::start_capture($seconds,$profile);$this->redirect();}
    public function stop(){$this->auth();Request_Monitor_Core::stop_capture();$this->redirect();}
    public function repair(){$this->auth();Request_Monitor_Core::install_mu();$this->redirect();}
    public function clear(){$this->auth();Request_Monitor_Store::clear_logs();$this->redirect();}
    public function download(){$this->auth();Request_Monitor_Store::ensure_log();header('Content-Type: application/x-ndjson');header('Content-Disposition: attachment; filename="request-monitor-'.gmdate('Ymd-His').'.jsonl"');$fh=@fopen(Request_Monitor_Store::log_file(),'rb');if($fh){fgets($fh);while(!feof($fh))echo fread($fh,1048576);fclose($fh);}exit;}
    private function badge($class){$colors=array('CPU_BOUND'=>'#b32d2e','WAIT_BOUND'=>'#996800','MIXED'=>'#7a5b00','FAST'=>'#2271b1','ACTIVE'=>'#8a2424','UNKNOWN'=>'#646970');$c=$colors[$class]??'#646970';return '<span style="display:inline-block;padding:2px 7px;border-radius:12px;background:'.esc_attr($c).';color:#fff;font-size:11px;font-weight:700">'.esc_html($class).'</span>';}
    private function details($row){echo '<details><summary>Inspect</summary><div style="min-width:760px">';if($row['state']==='ACTIVE'){$pid=(int)$row['pid'];foreach(array("ps -p $pid -o pid,ppid,user,stat,etime,time,%cpu,%mem,rss,wchan:32,cmd","timeout 5 strace -f -ttT -s 256 -p $pid","sudo phpspy --pid=$pid --limit=200","lsof -nP -p $pid") as $cmd)echo '<p><code>'.esc_html($cmd).'</code></p>';}else{foreach(array('Fingerprints'=>array('request'=>$row['request_fingerprint'],'pattern'=>$row['pattern_fingerprint'],'query'=>$row['query_fingerprint'],'query_shape'=>$row['query_shape_fingerprint'],'pattern_path'=>$row['pattern_path']),'Hook / callback profile'=>$row['hooks'],'Lifecycle phases'=>$row['phases'],'Coverage'=>$row['coverage'],'WordPress context'=>$row['wp'],'Resource deltas'=>$row['resources'],'Included code'=>$row['groups'],'SQL'=>$row['sql'],'Outbound HTTP'=>$row['http']) as $title=>$data)echo '<p><strong>'.esc_html($title).'</strong></p><pre style="white-space:pre-wrap">'.esc_html(wp_json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre>';}echo '</div></details>';}

    public function render(){
        if(!current_user_can('manage_options'))return;$healthy=Request_Monitor_Core::mu_healthy();$capture=Request_Monitor_Core::capture_state();$slow=(int)get_option(Request_Monitor_Core::OPT_SLOW_MS,1500);$floor=(float)get_option(Request_Monitor_Core::OPT_CALLBACK_FLOOR,5);$max=(int)get_option(Request_Monitor_Core::OPT_MAX_MB,25);$scope=Request_Monitor_Core::get_scope();$session=$capture['session']?:null;$rows=Request_Monitor_Store::build_rows(null,$session);$groups=Request_Monitor_Store::fingerprint_groups('pattern',1,false,$session);usort($groups,function($a,$b){return $b['total_cpu_ms']<=>$a['total_cpu_ms'];});
        ?>
        <div class="wrap"><h1>Request Monitor <small style="font-size:14px;color:#646970">v<?php echo esc_html(Request_Monitor_Core::VERSION);?></small></h1>
        <p><strong>Snapshot-only instrumentation.</strong> Continuous monitoring is not available. WP-CLI is the recommended control plane.</p>
        <div style="background:#fff;border:1px solid #ccd0d4;padding:12px;margin:12px 0"><strong>MU foundation:</strong> <?php echo $healthy?'<span style="color:green">HEALTHY</span>':'<span style="color:#b32d2e">MISSING / OUTDATED</span>';?> &nbsp; <strong>State:</strong> <?php echo esc_html(strtoupper($capture['state']));?> <?php if($capture['active']):?> &nbsp; <?php echo esc_html($capture['seconds_remaining']);?>s remaining &nbsp; profile=<code><?php echo esc_html($capture['profile']);?></code> &nbsp; session=<code><?php echo esc_html($capture['session']);?></code> <a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=rrt_stop'),self::NONCE));?>">Stop now</a><?php endif;?></div>

        <form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" style="background:#fff;border:1px solid #ccd0d4;padding:14px;margin-bottom:12px"><?php wp_nonce_field(self::NONCE);?><input type="hidden" name="action" value="rrt_capture"><h2>Take snapshot</h2><label>Duration <input type="number" name="duration" value="30" min="5" max="300" style="width:80px"> seconds</label>&nbsp;&nbsp;<label>Profile <select name="profile"><option value="light">light — fingerprints/PID/CPU/wall/resources</option><option value="hooks">hooks — adds hook timing + slow callback escalation</option><option value="deep">deep — hooks/callbacks + SQL from start</option></select></label>&nbsp;&nbsp;<label><input type="checkbox" name="keep_log" value="1"> keep previous log</label><?php submit_button('Start bounded snapshot','primary','submit',false);?></form>

        <form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" style="background:#fff;border:1px solid #ccd0d4;padding:14px"><?php wp_nonce_field(self::NONCE);?><input type="hidden" name="action" value="rrt_settings"><h2>Capture settings</h2><label>Slow threshold <input name="slow_ms" type="number" min="250" max="60000" value="<?php echo esc_attr($slow);?>" style="width:90px"> ms</label>&nbsp;&nbsp;<label>Callback floor <input name="callback_floor" type="number" min="0.1" max="1000" step="0.1" value="<?php echo esc_attr($floor);?>" style="width:80px"> ms</label>&nbsp;&nbsp;<label>Log <input name="max_mb" type="number" min="1" max="250" value="<?php echo esc_attr($max);?>" style="width:70px"> MB</label>
        <h3>Trace scope</h3><p><?php foreach(array('front','admin','ajax','rest','cron','cli') as $type):?><label style="margin-right:12px"><input type="checkbox" name="scope_types[]" value="<?php echo esc_attr($type);?>" <?php checked(in_array($type,$scope['types'],true));?>> <?php echo esc_html($type);?></label><?php endforeach;?></p><p><label>Methods (empty = all)<br><input name="scope_methods" value="<?php echo esc_attr(implode(',',$scope['methods']));?>" style="width:520px"></label></p>
        <?php foreach(array('include_paths'=>'Include paths (glob, one per line)','exclude_paths'=>'Exclude paths','include_actions'=>'Include AJAX/WC actions','exclude_actions'=>'Exclude actions') as $key=>$label):?><p><label><?php echo esc_html($label);?><br><textarea name="<?php echo esc_attr($key);?>" rows="2" style="width:600px"><?php echo esc_textarea(implode("\n",$scope[$key]));?></textarea></label></p><?php endforeach;?><?php submit_button('Save settings','secondary','submit',false);?></form>

        <p><a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=rrt_download'),self::NONCE));?>">Download JSONL</a> <a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=rrt_clear'),self::NONCE));?>">Clear logs</a></p>
        <h2>Latest snapshot fingerprints</h2><table class="widefat striped"><thead><tr><th>Fingerprint</th><th>Pattern</th><th>Count</th><th>Slow</th><th>Avg wall</th><th>Total CPU</th></tr></thead><tbody><?php foreach(array_slice($groups,0,25) as $g):?><tr><td><code><?php echo esc_html($g['fingerprint']);?></code></td><td><code><?php echo esc_html($g['pattern_path']);?></code></td><td><?php echo esc_html($g['count']);?></td><td><?php echo esc_html($g['slow']);?></td><td><?php echo esc_html($g['avg_wall_ms']);?> ms</td><td><?php echo esc_html($g['total_cpu_ms']);?> ms</td></tr><?php endforeach;?></tbody></table>
        <h2>Latest snapshot requests</h2><div style="overflow:auto"><table class="widefat striped" style="min-width:1750px"><thead><tr><th>Class</th><th>Profile</th><th>Type</th><th>Pattern FP</th><th>PID</th><th>Method</th><th>Path</th><th>Action</th><th>Wall</th><th>CPU</th><th>IP</th><th>CF-Ray</th><th>Details</th></tr></thead><tbody><?php foreach(array_slice($rows,0,300) as $r):?><tr><td><?php echo $this->badge($r['class']);?></td><td><code><?php echo esc_html($r['profile']);?></code></td><td><?php echo esc_html($r['type']);?></td><td><code><?php echo esc_html($r['pattern_fingerprint']);?></code></td><td><code><?php echo esc_html($r['pid']);?></code></td><td><?php echo esc_html($r['method']);?></td><td><code><?php echo esc_html($r['path']);?></code></td><td><code><?php echo esc_html($r['action']);?></code></td><td><?php echo $r['wall']!==null?esc_html(round($r['wall'],1).' ms'):'—';?></td><td><?php echo $r['cpu']!==null?esc_html(round($r['cpu'],1).' ms'):'—';?></td><td><?php echo esc_html($r['ip']);?></td><td><code><?php echo esc_html($r['ray']);?></code></td><td><?php $this->details($r);?></td></tr><?php endforeach;?></tbody></table></div></div><?php
    }
}
