<?php
if (!defined('ABSPATH')) exit;

final class Request_Monitor_Admin {
    const NONCE='rrt_admin_action';private static $instance=null;
    public static function instance(){if(self::$instance===null)self::$instance=new self();return self::$instance;}
    private function __construct(){add_action('admin_init',array($this,'ensure_mu'));add_action('admin_menu',array($this,'menu'));foreach(array('save','capture','stop','clear','download','repair') as $a)add_action('admin_post_rrt_'.$a,array($this,$a));}
    public function ensure_mu(){if(current_user_can('manage_options')&&!Request_Monitor_Core::mu_healthy())Request_Monitor_Core::install_mu();}
    public function menu(){add_management_page('Request Monitor','Request Monitor','manage_options','rocket-request-tracer',array($this,'render'));}
    private function auth(){if(!current_user_can('manage_options'))wp_die('Insufficient permissions.');check_admin_referer(self::NONCE);}
    private function redirect($msg=''){wp_safe_redirect(admin_url('tools.php?page=rocket-request-tracer'.($msg?'&rrt_msg='.rawurlencode($msg):'')));exit;}
    public function save(){$this->auth();update_option(Request_Monitor_Core::OPT_MAX_MB,max(1,min(250,(int)($_POST['max_mb']??25))),false);update_option(Request_Monitor_Core::OPT_SLOW_MS,max(250,min(60000,(int)($_POST['slow_ms']??1500))),false);update_option(Request_Monitor_Core::OPT_CALLBACK_FLOOR,max(0.1,min(1000,(float)($_POST['callback_floor']??5))),false);update_option(Request_Monitor_Core::OPT_SQL_STACK_MS,max(1,min(1000,(float)($_POST['sql_stack_ms']??10))),false);Request_Monitor_Core::save_scope(array('types'=>$_POST['scope_types']??array(),'methods'=>$_POST['scope_methods']??'','include_paths'=>$_POST['include_paths']??'','exclude_paths'=>$_POST['exclude_paths']??'','include_actions'=>$_POST['include_actions']??'','exclude_actions'=>$_POST['exclude_actions']??''));$this->redirect('Settings saved.');}
    public function capture(){$this->auth();$seconds=Request_Monitor_Core::parse_duration($_POST['duration']??'30s');$profile=(string)($_POST['profile']??'light');if(!$seconds||Request_Monitor_Core::validate_profile($profile)===null)$this->redirect('Invalid capture duration or profile.');Request_Monitor_Store::clear_logs();$r=Request_Monitor_Core::start_capture($seconds,$profile);if(is_wp_error($r))$this->redirect($r->get_error_message());$this->redirect('Snapshot '.$r['session'].' started. It will expire automatically.');}
    public function stop(){$this->auth();Request_Monitor_Core::stop_capture();$this->redirect('Capture stopped.');}
    public function clear(){$this->auth();Request_Monitor_Store::clear_logs();$this->redirect('Logs cleared.');}
    public function repair(){$this->auth();$r=Request_Monitor_Core::install_mu();$this->redirect(is_wp_error($r)?$r->get_error_message():'MU foundation repaired.');}
    public function download(){$this->auth();Request_Monitor_Store::ensure_log();header('Content-Type: application/x-ndjson');header('Content-Disposition: attachment; filename="request-monitor-'.gmdate('Ymd-His').'.jsonl"');$fh=@fopen(Request_Monitor_Store::log_file(),'rb');if($fh){fgets($fh);while(!feof($fh))echo fread($fh,1048576);fclose($fh);}exit;}

    public function render(){
        if(!current_user_can('manage_options'))return;$state=Request_Monitor_Core::capture_state();$scope=Request_Monitor_Core::get_scope();$healthy=Request_Monitor_Core::mu_healthy();$analysis=Request_Monitor_Analyzer::analyze('last',null,8);
        echo '<div class="wrap"><h1>Request Monitor <small style="font-size:14px;color:#646970">v'.esc_html(Request_Monitor_Core::VERSION).'</small></h1>';
        if(!empty($_GET['rrt_msg']))echo '<div class="notice notice-info"><p>'.esc_html(wp_unslash($_GET['rrt_msg'])).'</p></div>';
        echo '<p><strong>MU foundation:</strong> '.($healthy?'<span style="color:green">HEALTHY</span>':'<span style="color:#b32d2e">MISSING / OUTDATED</span>').' &nbsp; <strong>State:</strong> '.esc_html($state['state']).($state['active']?' ('.$state['seconds_remaining'].'s remaining, '.$state['profile'].')':'').'</p>';
        echo '<div style="display:flex;gap:16px;flex-wrap:wrap">';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="background:#fff;border:1px solid #ccd0d4;padding:14px;min-width:360px">';wp_nonce_field(self::NONCE);echo '<input type="hidden" name="action" value="rrt_capture"><h2>Bounded snapshot</h2><p><label>Duration <input name="duration" value="30s" style="width:80px"></label> <label>Profile <select name="profile"><option value="light">light</option><option value="hooks">hooks</option><option value="deep">deep</option></select></label></p><p><button class="button button-primary">Start snapshot</button></p><p>Hard limit: 5–300 seconds. Capture expires even if this page is closed.</p></form>';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="background:#fff;border:1px solid #ccd0d4;padding:14px;min-width:520px">';wp_nonce_field(self::NONCE);echo '<input type="hidden" name="action" value="rrt_save"><h2>Tracing settings</h2><p><label>Slow threshold <input name="slow_ms" type="number" value="'.esc_attr(get_option(Request_Monitor_Core::OPT_SLOW_MS,1500)).'" style="width:90px"> ms</label> &nbsp; <label>Callback floor <input name="callback_floor" type="number" step="0.1" value="'.esc_attr(get_option(Request_Monitor_Core::OPT_CALLBACK_FLOOR,5)).'" style="width:80px"> ms</label> &nbsp; <label>Slow SQL stack <input name="sql_stack_ms" type="number" step="1" value="'.esc_attr(get_option(Request_Monitor_Core::OPT_SQL_STACK_MS,10)).'" style="width:70px"> ms</label></p>';
        echo '<p>';foreach(array('front','admin','ajax','rest','cron','cli') as $type)echo '<label style="margin-right:10px"><input type="checkbox" name="scope_types[]" value="'.esc_attr($type).'" '.checked(in_array($type,$scope['types'],true),true,false).'> '.esc_html($type).'</label>';echo '</p><p><label>Methods<br><input name="scope_methods" value="'.esc_attr(implode(',',$scope['methods'])).'" style="width:500px"></label></p>';
        foreach(array('include_paths'=>'Include paths','exclude_paths'=>'Exclude paths','include_actions'=>'Include actions','exclude_actions'=>'Exclude actions') as $k=>$label)echo '<p><label>'.esc_html($label).'<br><textarea name="'.esc_attr($k).'" rows="2" style="width:500px">'.esc_textarea(implode("\n",$scope[$k])).'</textarea></label></p>';
        echo '<p><label>Max log <input name="max_mb" type="number" value="'.esc_attr(get_option(Request_Monitor_Core::OPT_MAX_MB,25)).'" style="width:70px"> MB</label></p><button class="button button-primary">Save settings</button></form></div>';
        echo '<p>';foreach(array('stop'=>'Stop now','download'=>'Download JSONL','clear'=>'Clear logs','repair'=>'Repair MU') as $a=>$label)echo '<a class="button" style="margin-right:6px" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=rrt_'.$a),self::NONCE)).'">'.esc_html($label).'</a>';echo '</p>';
        $s=$analysis['summary']??array();echo '<h2>Last snapshot analysis</h2><p>Completed: '.esc_html($s['completed']??0).' | Active: '.esc_html($s['active']??0).' | PHP CPU: '.esc_html(round(($s['total_cpu_ms']??0)/1000,2)).'s | SQL: '.esc_html(round(($s['total_sql_ms']??0)/1000,2)).'s | HTTP: '.esc_html(round(($s['total_http_ms']??0)/1000,2)).'s</p>';
        if(!empty($analysis['conclusions'])){echo '<ol>';foreach($analysis['conclusions'] as $c)echo '<li>'.esc_html($c).'</li>';echo '</ol>';}
        $this->simple_table('Top request families',$analysis['workloads']??array(),array('fingerprint','pattern','count','avg_wall_ms','avg_cpu_ms','cpu_share_pct','total_sql_ms','total_http_ms'));
        $this->simple_table('Top PHP callbacks',$analysis['php']['callbacks']??array(),array('total_ms','count','owner','hook','callable','file','line'));
        $this->simple_table('Top SQL',$analysis['sql']??array(),array('query_hash','count','total_ms','max_ms','dominant_owner','dominant_caller','query'));
        echo '<p><code>wp request-monitor analyze --session=last</code> provides the full CLI analysis and stacks.</p></div>';
    }
    private function simple_table($title,$rows,$keys){if(!$rows)return;echo '<h3>'.esc_html($title).'</h3><div style="overflow:auto"><table class="widefat striped"><thead><tr>';foreach($keys as $k)echo '<th>'.esc_html($k).'</th>';echo '</tr></thead><tbody>';foreach(array_slice($rows,0,10) as $r){echo '<tr>';foreach($keys as $k){$v=$r[$k]??'';if(is_array($v))$v=wp_json_encode($v);echo '<td><code>'.esc_html((string)$v).'</code></td>';}echo '</tr>';}echo '</tbody></table></div>';}
}
