<?php
if (!defined('ABSPATH')) exit;

final class Request_Monitor_Analyzer {
    public static function analyze($session='last',$fingerprint=null,$limit=10){
        $session=Request_Monitor_Store::resolve_session($session);$limit=max(1,min(50,(int)$limit));
        $rows=$fingerprint?Request_Monitor_Store::rows_for_fingerprint($fingerprint,$session):Request_Monitor_Store::build_rows(null,$session);
        $done=array_values(array_filter($rows,function($r){return $r['state']==='DONE';}));
        $active=array_values(array_filter($rows,function($r){return $r['state']==='ACTIVE';}));
        if(!$rows)return array('session'=>$session,'fingerprint'=>$fingerprint,'summary'=>array('completed'=>0,'active'=>0),'conclusions'=>array('No traced requests were found for this selection.'));

        $profile=$rows[0]['profile']??'unknown';$capture_seconds=self::capture_seconds($rows);
        $summary=array('completed'=>count($done),'active'=>count($active),'slow'=>0,'cpu_bound'=>0,'mixed'=>0,'wait_bound'=>0,'fast'=>0,'total_wall_ms'=>0.0,'total_cpu_ms'=>0.0,'total_sql_ms'=>0.0,'total_http_ms'=>0.0,'estimated_other_wait_ms'=>0.0,'peak_memory_mb'=>0.0,'capture_seconds'=>$capture_seconds,'estimated_cpu_core_demand'=>null,'avg_cpu_share_pct'=>null);
        $callbacks=array();$owners=array();$hooks=array();$queries=array();$http=array();$phases=array();$workloads=array();$actions=array();$savequeries_warnings=array();

        foreach($done as $row){
            $summary['slow']+=!empty($row['slow'])?1:0;$class=strtolower((string)$row['class']);if(isset($summary[$class]))$summary[$class]++;
            $wall=(float)$row['wall'];$cpu=(float)$row['cpu'];$sql_ms=(float)($row['sql']['total_ms']??0);$http_ms=(float)($row['http']['total_ms']??0);
            $summary['total_wall_ms']+=$wall;$summary['total_cpu_ms']+=$cpu;$summary['total_sql_ms']+=$sql_ms;$summary['total_http_ms']+=$http_ms;$summary['peak_memory_mb']=max($summary['peak_memory_mb'],(float)$row['memory']);
            $wait=max(0,$wall-$cpu);$summary['estimated_other_wait_ms']+=max(0,$wait-$sql_ms-$http_ms);
            if(isset($row['sql']['enabled'])&&!$row['sql']['enabled']&&!empty($row['sql']['reason']))$savequeries_warnings[$row['sql']['reason']]=true;
            self::aggregate_hook_profile($row,$callbacks,$owners,$hooks);
            self::aggregate_sql($row,$queries);
            self::aggregate_http($row,$http);
            self::aggregate_phases($row,$phases);
            self::aggregate_workload($row,$workloads);self::aggregate_action($row,$actions);
        }

        foreach(array('total_wall_ms','total_cpu_ms','total_sql_ms','total_http_ms','estimated_other_wait_ms','peak_memory_mb') as $k)$summary[$k]=round($summary[$k],2);
        if($summary['total_wall_ms']>0)$summary['avg_cpu_share_pct']=round(($summary['total_cpu_ms']/$summary['total_wall_ms'])*100,1);
        if($capture_seconds>0)$summary['estimated_cpu_core_demand']=round($summary['total_cpu_ms']/($capture_seconds*1000),2);

        $workloads=self::finish_workloads($workloads,$limit);$actions=self::finish_workloads($actions,$limit);$callbacks=self::finish_metric_rows($callbacks,$limit);$owners=self::finish_metric_rows($owners,$limit);$hooks=self::finish_metric_rows($hooks,$limit);$queries=self::finish_query_rows($queries,$limit);$http=self::finish_http_rows($http,$limit);$phases=self::finish_metric_rows($phases,$limit);
        $conclusions=self::conclusions($summary,$workloads,$callbacks,$queries,$http,$owners,$savequeries_warnings,$profile,$fingerprint);

        $slowest=array_slice(array_map(function($r){return array('pid'=>$r['pid'],'method'=>$r['method'],'path'=>$r['path'],'action'=>$r['action'],'wall_ms'=>round((float)$r['wall'],2),'cpu_ms'=>round((float)$r['cpu'],2),'sql_ms'=>round((float)($r['sql']['total_ms']??0),2),'http_ms'=>round((float)($r['http']['total_ms']??0),2),'class'=>$r['class'],'cf_ray'=>$r['ray']);},$done),0,$limit);
        return array('session'=>$session,'profile'=>$profile,'fingerprint'=>$fingerprint,'summary'=>$summary,'workloads'=>$workloads,'actions'=>$actions,'slowest_requests'=>$slowest,'php'=>array('callbacks'=>$callbacks,'owners'=>$owners,'hooks'=>$hooks),'sql'=>$queries,'http'=>$http,'lifecycle'=>$phases,'warnings'=>array_keys($savequeries_warnings),'conclusions'=>$conclusions,'active_requests'=>array_slice(array_map(function($r){return array('pid'=>$r['pid'],'method'=>$r['method'],'path'=>$r['path'],'action'=>$r['action'],'started_utc'=>$r['timestamp']);},$active),0,$limit));
    }

    private static function capture_seconds($rows){foreach($rows as $r){$s=(int)($r['capture_started']??0);$u=(int)($r['capture_until']??0);if($s>0&&$u>$s)return $u-$s;}return (int)get_option(Request_Monitor_Core::OPT_CAPTURE_DURATION,0);}

    private static function aggregate_workload($row,&$groups){$key=$row['pattern_fingerprint'];if(!$key)return;if(!isset($groups[$key]))$groups[$key]=array('fingerprint'=>$key,'pattern'=>$row['pattern_path'],'action'=>$row['action'],'count'=>0,'slow'=>0,'cpu_bound'=>0,'mixed'=>0,'wait_bound'=>0,'total_wall_ms'=>0.0,'total_cpu_ms'=>0.0,'total_sql_ms'=>0.0,'total_http_ms'=>0.0,'max_wall_ms'=>0.0,'peak_memory_mb'=>0.0);$g=&$groups[$key];$g['count']++;if($row['slow'])$g['slow']++;if($row['class']==='CPU_BOUND')$g['cpu_bound']++;elseif($row['class']==='MIXED')$g['mixed']++;elseif($row['class']==='WAIT_BOUND')$g['wait_bound']++;$g['total_wall_ms']+=(float)$row['wall'];$g['total_cpu_ms']+=(float)$row['cpu'];$g['total_sql_ms']+=(float)($row['sql']['total_ms']??0);$g['total_http_ms']+=(float)($row['http']['total_ms']??0);$g['max_wall_ms']=max($g['max_wall_ms'],(float)$row['wall']);$g['peak_memory_mb']=max($g['peak_memory_mb'],(float)$row['memory']);}

    private static function aggregate_action($row,&$groups){$action=(string)$row['action'];if($action==='')return;$key=substr(hash('sha256','action|'.$action),0,20);if(!isset($groups[$key]))$groups[$key]=array('fingerprint'=>$key,'pattern'=>'action:'.$action,'action'=>$action,'count'=>0,'slow'=>0,'cpu_bound'=>0,'mixed'=>0,'wait_bound'=>0,'total_wall_ms'=>0.0,'total_cpu_ms'=>0.0,'total_sql_ms'=>0.0,'total_http_ms'=>0.0,'max_wall_ms'=>0.0,'peak_memory_mb'=>0.0);$g=&$groups[$key];$g['count']++;if($row['slow'])$g['slow']++;if($row['class']==='CPU_BOUND')$g['cpu_bound']++;elseif($row['class']==='MIXED')$g['mixed']++;elseif($row['class']==='WAIT_BOUND')$g['wait_bound']++;$g['total_wall_ms']+=(float)$row['wall'];$g['total_cpu_ms']+=(float)$row['cpu'];$g['total_sql_ms']+=(float)($row['sql']['total_ms']??0);$g['total_http_ms']+=(float)($row['http']['total_ms']??0);$g['max_wall_ms']=max($g['max_wall_ms'],(float)$row['wall']);$g['peak_memory_mb']=max($g['peak_memory_mb'],(float)$row['memory']);}

    private static function aggregate_hook_profile($row,&$callbacks,&$owners,&$hooks){$p=$row['hooks']??array();foreach((array)($p['top_callbacks']??array()) as $c){$key=sha1(($c['owner']??'').'|'.($c['callable']??'').'|'.($c['hook']??'').'|'.($c['priority']??'').'|'.($c['file']??'').'|'.($c['line']??''));if(!isset($callbacks[$key]))$callbacks[$key]=array('owner'=>$c['owner']??'','callable'=>$c['callable']??'','hook'=>$c['hook']??'','priority'=>$c['priority']??null,'file'=>$c['file']??'','line'=>$c['line']??null,'count'=>0,'request_count'=>0,'total_ms'=>0.0,'max_ms'=>0.0);$callbacks[$key]['count']+=(int)($c['count']??0);$callbacks[$key]['request_count']++;$callbacks[$key]['total_ms']+=(float)($c['total_ms']??0);$callbacks[$key]['max_ms']=max($callbacks[$key]['max_ms'],(float)($c['max_ms']??0));}
        foreach((array)($p['top_owners']??array()) as $o){$key=$o['owner']??'unknown';if(!isset($owners[$key]))$owners[$key]=array('owner'=>$key,'count'=>0,'request_count'=>0,'total_ms'=>0.0,'max_ms'=>0.0);$owners[$key]['count']+=(int)($o['count']??0);$owners[$key]['request_count']++;$owners[$key]['total_ms']+=(float)($o['total_ms']??0);$owners[$key]['max_ms']=max($owners[$key]['max_ms'],(float)($o['max_ms']??0));}
        foreach((array)($p['top_hooks']??array()) as $h){$key=$h['hook']??'unknown';if(!isset($hooks[$key]))$hooks[$key]=array('hook'=>$key,'count'=>0,'request_count'=>0,'total_ms'=>0.0,'max_ms'=>0.0);$hooks[$key]['count']+=(int)($h['count']??0);$hooks[$key]['request_count']++;$hooks[$key]['total_ms']+=(float)($h['total_ms']??0);$hooks[$key]['max_ms']=max($hooks[$key]['max_ms'],(float)($h['max_ms']??0));}}

    private static function aggregate_sql($row,&$queries){foreach((array)($row['sql']['top_groups']??array()) as $q){$key=$q['query_hash']??'';if(!$key)continue;if(!isset($queries[$key]))$queries[$key]=array('query_hash'=>$key,'query'=>$q['query']??'','count'=>0,'request_count'=>0,'total_ms'=>0.0,'max_ms'=>0.0,'dominant_caller'=>$q['dominant_caller']??'','dominant_owner'=>$q['dominant_owner']??'','sample_stack'=>$q['sample_stack']??array());$queries[$key]['count']+=(int)($q['count']??0);$queries[$key]['request_count']++;$queries[$key]['total_ms']+=(float)($q['total_ms']??0);$queries[$key]['max_ms']=max($queries[$key]['max_ms'],(float)($q['max_ms']??0));if(empty($queries[$key]['sample_stack'])&&!empty($q['sample_stack']))$queries[$key]['sample_stack']=$q['sample_stack'];}}
    private static function aggregate_http($row,&$http){foreach((array)($row['http']['groups']??array()) as $h){$key=$h['http_hash']??sha1(($h['url']??'').'|'.($h['owner']??'').'|'.($h['caller']??''));if(!isset($http[$key]))$http[$key]=array('url'=>$h['url']??'','owner'=>$h['owner']??'','caller'=>$h['caller']??'','count'=>0,'request_count'=>0,'total_ms'=>0.0,'max_ms'=>0.0,'sample_stack'=>$h['sample_stack']??array(),'transport'=>$h['transport']??'');$http[$key]['count']+=(int)($h['count']??0);$http[$key]['request_count']++;$http[$key]['total_ms']+=(float)($h['total_ms']??0);$http[$key]['max_ms']=max($http[$key]['max_ms'],(float)($h['max_ms']??0));}}
    private static function aggregate_phases($row,&$phases){foreach((array)$row['phases'] as $name=>$ms){if(!is_numeric($ms))continue;if(!isset($phases[$name]))$phases[$name]=array('phase'=>$name,'count'=>0,'total_ms'=>0.0,'max_ms'=>0.0);$phases[$name]['count']++;$phases[$name]['total_ms']+=(float)$ms;$phases[$name]['max_ms']=max($phases[$name]['max_ms'],(float)$ms);}}

    private static function finish_workloads($rows,$limit){$out=array_values($rows);foreach($out as &$r){$r['avg_wall_ms']=$r['count']?round($r['total_wall_ms']/$r['count'],2):0;$r['avg_cpu_ms']=$r['count']?round($r['total_cpu_ms']/$r['count'],2):0;$r['cpu_share_pct']=$r['total_wall_ms']>0?round(($r['total_cpu_ms']/$r['total_wall_ms'])*100,1):0;$wait=max(0,$r['total_wall_ms']-$r['total_cpu_ms']);$r['estimated_other_wait_ms']=round(max(0,$wait-$r['total_sql_ms']-$r['total_http_ms']),2);foreach(array('total_wall_ms','total_cpu_ms','total_sql_ms','total_http_ms','max_wall_ms','peak_memory_mb') as $k)$r[$k]=round($r[$k],2);}unset($r);usort($out,function($a,$b){return $b['total_cpu_ms']<=>$a['total_cpu_ms'];});return array_slice($out,0,$limit);}
    private static function finish_metric_rows($rows,$limit){$out=array_values($rows);foreach($out as &$r){$r['total_ms']=round((float)$r['total_ms'],2);$r['max_ms']=round((float)$r['max_ms'],2);$r['avg_ms']=!empty($r['count'])?round($r['total_ms']/$r['count'],2):0;}unset($r);usort($out,function($a,$b){return $b['total_ms']<=>$a['total_ms'];});return array_slice($out,0,$limit);}
    private static function finish_query_rows($rows,$limit){$out=array_values($rows);foreach($out as &$r){$r['total_ms']=round($r['total_ms'],2);$r['max_ms']=round($r['max_ms'],2);$r['avg_ms']=$r['count']?round($r['total_ms']/$r['count'],2):0;}unset($r);usort($out,function($a,$b){return $b['total_ms']<=>$a['total_ms'];});return array_slice($out,0,$limit);}
    private static function finish_http_rows($rows,$limit){return self::finish_query_rows($rows,$limit);}

    private static function conclusions($s,$workloads,$callbacks,$queries,$http,$owners,$warnings,$profile,$fingerprint){$out=array();if($s['completed']===0){$out[]='No completed requests were available yet; wait for in-flight requests to finish and run analyze again.';return $out;}if(!$fingerprint&&!empty($workloads[0])){$w=$workloads[0];$out[]=sprintf('Dominant request family %s consumed %.2f CPU seconds across %d completed requests (%.1f%% CPU share of its aggregate wall time).',$w['pattern'],$w['total_cpu_ms']/1000,$w['count'],$w['cpu_share_pct']);}
        if($s['estimated_cpu_core_demand']!==null)$out[]=sprintf('The completed requests represent approximately %.2f CPU cores of demand across the capture window; this is an aggregate diagnostic estimate, not host-wide utilization.',$s['estimated_cpu_core_demand']);
        if($s['avg_cpu_share_pct']!==null){if($s['avg_cpu_share_pct']>=70)$out[]='The workload is predominantly PHP CPU-bound.';elseif($s['avg_cpu_share_pct']<=25)$out[]='The workload is predominantly wait-bound; database, outbound HTTP, locks, cache, or filesystem waits deserve priority.';else $out[]='The workload is mixed: PHP execution and waiting both materially contribute.';}
        if(!empty($queries[0]))$out[]=sprintf('Top SQL fingerprint %s accounts for %.2f ms across %d executions; dominant caller: %s.',$queries[0]['query_hash'],$queries[0]['total_ms'],$queries[0]['count'],$queries[0]['dominant_caller']?:'unknown');
        elseif($profile==='deep')$out[]='Deep mode did not produce query groups. Check the SQL coverage/warnings section; SAVEQUERIES may have been defined false before Request Monitor could enable it.';
        if(!empty($callbacks[0]))$out[]=sprintf('Top timed PHP callback is %s (%s) with %.2f ms observed across %d calls.',$callbacks[0]['callable'],$callbacks[0]['owner'],$callbacks[0]['total_ms'],$callbacks[0]['count']);
        if(!empty($owners[0]))$out[]=sprintf('Largest timed application owner is %s with %.2f ms of observed callback time.',$owners[0]['owner'],$owners[0]['total_ms']);
        if(!empty($http[0]))$out[]=sprintf('Top outbound HTTP dependency is %s with %.2f ms across %d calls.',$http[0]['url'],$http[0]['total_ms'],$http[0]['count']);
        if($s['estimated_other_wait_ms']>0)$out[]=sprintf('After subtracting measured PHP CPU, SQL, and outbound HTTP timers, %.2f ms of aggregate wall time remains unattributed. Treat this as a residual estimate; timers can overlap and it may include Redis/cache/filesystem/socket/lock waits.',$s['estimated_other_wait_ms']);
        foreach($warnings as $w)$out[]='SQL warning: '.$w.'.';return $out;}
}
